services:
  - type: web
    name: fangpa-yyds
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader wordnet omw-1.4 -d nltk_data
    startCommand: gunicorn cet4_web:app
